/**
 * GSPNS / NSmart Public Transport API (Novi Sad)
 * Unofficial documentation of the reverse-engineered API behind the GSPNS (JGSP \"Novi Sad\") public transport network — the same API used by the **NSmart** mobile app (`buslogic.nsmartapp`).  The API is served by **BusLogic/NSmart** (`online.nsmart.rs`) and provides:  * the static transport network (cities → stations → line pairs), * real-time vehicle positions and arrival predictions per station, * electronic ticketing / wallet / card management endpoints (login, e-wallet, top-up…).  ## Reverse engineering provenance  * Endpoint paths, class names and the shared API key were recovered from the   NSmart 4.6 Android APK (see [FmasterofU/NSmart-RE](https://github.com/FmasterofU/NSmart-RE)). * Response schemas below were verified against the live API in September 2026. * The API key (`4670f468049bbee2260`) is compiled into the public APK as   `company_api_key` and is the same for every install — treat it as public knowledge.  ## Authentication  Every request must send the header:  ``` X-Api-Authentication: 4670f468049bbee2260 ```  All endpoints in this document include that header in their `security` requirements.  ## Notes & quirks (learned the hard way)  * The giant network payload (`networkextended.php`) is **not valid JSON when served   over a slow connection** — the server truncates / corrupts the stream mid-body   (raw control characters, null-byte runs, dropped chunks). The NSmart app   apparently tolerates this; re-request until you get a parseable body. * `networkextended.php` ignores semantically different `action` values   (`get_network`, `get_trips`, `get_schedule` return the same cities payload as   `get_cities_extended`). * `announcement.php` returns `[{\"success\":false,\"code\":3}]` for an unknown   `station_uid`. * `ibfm=TM00000` means \"all lines\"; pass a line code (e.g. `7A`) to filter. * Serbian text is `UTF-8`; strings may come back with JS-style unicode escapes. 
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.26.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "jgsp/model/Announcement.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

Announcement::Announcement()
{
    m_Seconds_left = 0;
    m_Seconds_leftIsSet = false;
    m_Line_number = utility::conversions::to_string_t("");
    m_Line_numberIsSet = false;
    m_Stations_gpsx = utility::conversions::to_string_t("");
    m_Stations_gpsxIsSet = false;
    m_Stations_gpsy = utility::conversions::to_string_t("");
    m_Stations_gpsyIsSet = false;
    m_Station_name = utility::conversions::to_string_t("");
    m_Station_nameIsSet = false;
    m_Actual_line_number = utility::conversions::to_string_t("");
    m_Actual_line_numberIsSet = false;
    m_Stations_between = 0;
    m_Stations_betweenIsSet = false;
    m_Garage_no = utility::conversions::to_string_t("");
    m_Garage_noIsSet = false;
    m_Line_title = utility::conversions::to_string_t("");
    m_Line_titleIsSet = false;
    m_Main_line_title = utility::conversions::to_string_t("");
    m_Main_line_titleIsSet = false;
    m_VehiclesIsSet = false;
    m_All_stationsIsSet = false;
    m_Station_uid = 0;
    m_Station_uidIsSet = false;
}

Announcement::~Announcement()
{
}

void Announcement::validate()
{
    // TODO: implement validation
}

web::json::value Announcement::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Seconds_leftIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("seconds_left"))] = ModelBase::toJson(m_Seconds_left);
    }
    if(m_Line_numberIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("line_number"))] = ModelBase::toJson(m_Line_number);
    }
    if(m_Stations_gpsxIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("stations_gpsx"))] = ModelBase::toJson(m_Stations_gpsx);
    }
    if(m_Stations_gpsyIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("stations_gpsy"))] = ModelBase::toJson(m_Stations_gpsy);
    }
    if(m_Station_nameIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("station_name"))] = ModelBase::toJson(m_Station_name);
    }
    if(m_Actual_line_numberIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("actual_line_number"))] = ModelBase::toJson(m_Actual_line_number);
    }
    if(m_Stations_betweenIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("stations_between"))] = ModelBase::toJson(m_Stations_between);
    }
    if(m_Garage_noIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("garage_no"))] = ModelBase::toJson(m_Garage_no);
    }
    if(m_Line_titleIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("line_title"))] = ModelBase::toJson(m_Line_title);
    }
    if(m_Main_line_titleIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("main_line_title"))] = ModelBase::toJson(m_Main_line_title);
    }
    if(m_VehiclesIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("vehicles"))] = ModelBase::toJson(m_Vehicles);
    }
    if(m_All_stationsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("all_stations"))] = ModelBase::toJson(m_All_stations);
    }
    if(m_Station_uidIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("station_uid"))] = ModelBase::toJson(m_Station_uid);
    }

    return val;
}

bool Announcement::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("seconds_left"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("seconds_left")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setSecondsLeft;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSecondsLeft);
            setSecondsLeft(refVal_setSecondsLeft);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("line_number"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("line_number")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setLineNumber;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLineNumber);
            setLineNumber(refVal_setLineNumber);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("stations_gpsx"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("stations_gpsx")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setStationsGpsx;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStationsGpsx);
            setStationsGpsx(refVal_setStationsGpsx);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("stations_gpsy"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("stations_gpsy")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setStationsGpsy;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStationsGpsy);
            setStationsGpsy(refVal_setStationsGpsy);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("station_name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("station_name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setStationName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStationName);
            setStationName(refVal_setStationName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("actual_line_number"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("actual_line_number")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setActualLineNumber;
            ok &= ModelBase::fromJson(fieldValue, refVal_setActualLineNumber);
            setActualLineNumber(refVal_setActualLineNumber);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("stations_between"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("stations_between")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setStationsBetween;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStationsBetween);
            setStationsBetween(refVal_setStationsBetween);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("garage_no"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("garage_no")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setGarageNo;
            ok &= ModelBase::fromJson(fieldValue, refVal_setGarageNo);
            setGarageNo(refVal_setGarageNo);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("line_title"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("line_title")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setLineTitle;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLineTitle);
            setLineTitle(refVal_setLineTitle);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("main_line_title"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("main_line_title")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setMainLineTitle;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMainLineTitle);
            setMainLineTitle(refVal_setMainLineTitle);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("vehicles"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("vehicles")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<VehiclePosition>> refVal_setVehicles;
            ok &= ModelBase::fromJson(fieldValue, refVal_setVehicles);
            setVehicles(refVal_setVehicles);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("all_stations"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("all_stations")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<Announcement_all_stations_inner>> refVal_setAllStations;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAllStations);
            setAllStations(refVal_setAllStations);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("station_uid"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("station_uid")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setStationUid;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStationUid);
            setStationUid(refVal_setStationUid);
            
        }
    }
    return ok;
}

void Announcement::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_Seconds_leftIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("seconds_left")), m_Seconds_left));
    }
    if(m_Line_numberIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("line_number")), m_Line_number));
    }
    if(m_Stations_gpsxIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("stations_gpsx")), m_Stations_gpsx));
    }
    if(m_Stations_gpsyIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("stations_gpsy")), m_Stations_gpsy));
    }
    if(m_Station_nameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("station_name")), m_Station_name));
    }
    if(m_Actual_line_numberIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("actual_line_number")), m_Actual_line_number));
    }
    if(m_Stations_betweenIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("stations_between")), m_Stations_between));
    }
    if(m_Garage_noIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("garage_no")), m_Garage_no));
    }
    if(m_Line_titleIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("line_title")), m_Line_title));
    }
    if(m_Main_line_titleIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("main_line_title")), m_Main_line_title));
    }
    if(m_VehiclesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("vehicles")), m_Vehicles));
    }
    if(m_All_stationsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("all_stations")), m_All_stations));
    }
    if(m_Station_uidIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("station_uid")), m_Station_uid));
    }
}

bool Announcement::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("seconds_left"))))
    {
        int32_t refVal_setSecondsLeft;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("seconds_left"))), refVal_setSecondsLeft );
        setSecondsLeft(refVal_setSecondsLeft);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("line_number"))))
    {
        utility::string_t refVal_setLineNumber;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("line_number"))), refVal_setLineNumber );
        setLineNumber(refVal_setLineNumber);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("stations_gpsx"))))
    {
        utility::string_t refVal_setStationsGpsx;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("stations_gpsx"))), refVal_setStationsGpsx );
        setStationsGpsx(refVal_setStationsGpsx);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("stations_gpsy"))))
    {
        utility::string_t refVal_setStationsGpsy;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("stations_gpsy"))), refVal_setStationsGpsy );
        setStationsGpsy(refVal_setStationsGpsy);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("station_name"))))
    {
        utility::string_t refVal_setStationName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("station_name"))), refVal_setStationName );
        setStationName(refVal_setStationName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("actual_line_number"))))
    {
        utility::string_t refVal_setActualLineNumber;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("actual_line_number"))), refVal_setActualLineNumber );
        setActualLineNumber(refVal_setActualLineNumber);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("stations_between"))))
    {
        int32_t refVal_setStationsBetween;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("stations_between"))), refVal_setStationsBetween );
        setStationsBetween(refVal_setStationsBetween);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("garage_no"))))
    {
        utility::string_t refVal_setGarageNo;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("garage_no"))), refVal_setGarageNo );
        setGarageNo(refVal_setGarageNo);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("line_title"))))
    {
        utility::string_t refVal_setLineTitle;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("line_title"))), refVal_setLineTitle );
        setLineTitle(refVal_setLineTitle);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("main_line_title"))))
    {
        utility::string_t refVal_setMainLineTitle;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("main_line_title"))), refVal_setMainLineTitle );
        setMainLineTitle(refVal_setMainLineTitle);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("vehicles"))))
    {
        std::vector<std::shared_ptr<VehiclePosition>> refVal_setVehicles;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("vehicles"))), refVal_setVehicles );
        setVehicles(refVal_setVehicles);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("all_stations"))))
    {
        std::vector<std::shared_ptr<Announcement_all_stations_inner>> refVal_setAllStations;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("all_stations"))), refVal_setAllStations );
        setAllStations(refVal_setAllStations);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("station_uid"))))
    {
        int32_t refVal_setStationUid;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("station_uid"))), refVal_setStationUid );
        setStationUid(refVal_setStationUid);
    }
    return ok;
}


int32_t Announcement::getSecondsLeft() const
{
    return m_Seconds_left;
}

void Announcement::setSecondsLeft(int32_t value)
{
    m_Seconds_left = value;
    m_Seconds_leftIsSet = true;
}

bool Announcement::secondsLeftIsSet() const
{
    return m_Seconds_leftIsSet;
}

void Announcement::unsetSeconds_left()
{
    m_Seconds_leftIsSet = false;
}
utility::string_t Announcement::getLineNumber() const
{
    return m_Line_number;
}


void Announcement::setLineNumber(const utility::string_t& value)
{
    m_Line_number = value;
    m_Line_numberIsSet = true;
}

bool Announcement::lineNumberIsSet() const
{
    return m_Line_numberIsSet;
}

void Announcement::unsetLine_number()
{
    m_Line_numberIsSet = false;
}
utility::string_t Announcement::getStationsGpsx() const
{
    return m_Stations_gpsx;
}


void Announcement::setStationsGpsx(const utility::string_t& value)
{
    m_Stations_gpsx = value;
    m_Stations_gpsxIsSet = true;
}

bool Announcement::stationsGpsxIsSet() const
{
    return m_Stations_gpsxIsSet;
}

void Announcement::unsetStations_gpsx()
{
    m_Stations_gpsxIsSet = false;
}
utility::string_t Announcement::getStationsGpsy() const
{
    return m_Stations_gpsy;
}


void Announcement::setStationsGpsy(const utility::string_t& value)
{
    m_Stations_gpsy = value;
    m_Stations_gpsyIsSet = true;
}

bool Announcement::stationsGpsyIsSet() const
{
    return m_Stations_gpsyIsSet;
}

void Announcement::unsetStations_gpsy()
{
    m_Stations_gpsyIsSet = false;
}
utility::string_t Announcement::getStationName() const
{
    return m_Station_name;
}


void Announcement::setStationName(const utility::string_t& value)
{
    m_Station_name = value;
    m_Station_nameIsSet = true;
}

bool Announcement::stationNameIsSet() const
{
    return m_Station_nameIsSet;
}

void Announcement::unsetStation_name()
{
    m_Station_nameIsSet = false;
}
utility::string_t Announcement::getActualLineNumber() const
{
    return m_Actual_line_number;
}


void Announcement::setActualLineNumber(const utility::string_t& value)
{
    m_Actual_line_number = value;
    m_Actual_line_numberIsSet = true;
}

bool Announcement::actualLineNumberIsSet() const
{
    return m_Actual_line_numberIsSet;
}

void Announcement::unsetActual_line_number()
{
    m_Actual_line_numberIsSet = false;
}
int32_t Announcement::getStationsBetween() const
{
    return m_Stations_between;
}

void Announcement::setStationsBetween(int32_t value)
{
    m_Stations_between = value;
    m_Stations_betweenIsSet = true;
}

bool Announcement::stationsBetweenIsSet() const
{
    return m_Stations_betweenIsSet;
}

void Announcement::unsetStations_between()
{
    m_Stations_betweenIsSet = false;
}
utility::string_t Announcement::getGarageNo() const
{
    return m_Garage_no;
}


void Announcement::setGarageNo(const utility::string_t& value)
{
    m_Garage_no = value;
    m_Garage_noIsSet = true;
}

bool Announcement::garageNoIsSet() const
{
    return m_Garage_noIsSet;
}

void Announcement::unsetGarage_no()
{
    m_Garage_noIsSet = false;
}
utility::string_t Announcement::getLineTitle() const
{
    return m_Line_title;
}


void Announcement::setLineTitle(const utility::string_t& value)
{
    m_Line_title = value;
    m_Line_titleIsSet = true;
}

bool Announcement::lineTitleIsSet() const
{
    return m_Line_titleIsSet;
}

void Announcement::unsetLine_title()
{
    m_Line_titleIsSet = false;
}
utility::string_t Announcement::getMainLineTitle() const
{
    return m_Main_line_title;
}


void Announcement::setMainLineTitle(const utility::string_t& value)
{
    m_Main_line_title = value;
    m_Main_line_titleIsSet = true;
}

bool Announcement::mainLineTitleIsSet() const
{
    return m_Main_line_titleIsSet;
}

void Announcement::unsetMain_line_title()
{
    m_Main_line_titleIsSet = false;
}
std::vector<std::shared_ptr<VehiclePosition>> Announcement::getVehicles() const
{
    return m_Vehicles;
}


void Announcement::setVehicles(const std::vector<std::shared_ptr<VehiclePosition>>& value)
{
    m_Vehicles = value;
    m_VehiclesIsSet = true;
}

bool Announcement::vehiclesIsSet() const
{
    return m_VehiclesIsSet;
}

void Announcement::unsetVehicles()
{
    m_VehiclesIsSet = false;
}
std::vector<std::shared_ptr<Announcement_all_stations_inner>> Announcement::getAllStations() const
{
    return m_All_stations;
}


void Announcement::setAllStations(const std::vector<std::shared_ptr<Announcement_all_stations_inner>>& value)
{
    m_All_stations = value;
    m_All_stationsIsSet = true;
}

bool Announcement::allStationsIsSet() const
{
    return m_All_stationsIsSet;
}

void Announcement::unsetAll_stations()
{
    m_All_stationsIsSet = false;
}
int32_t Announcement::getStationUid() const
{
    return m_Station_uid;
}

void Announcement::setStationUid(int32_t value)
{
    m_Station_uid = value;
    m_Station_uidIsSet = true;
}

bool Announcement::stationUidIsSet() const
{
    return m_Station_uidIsSet;
}

void Announcement::unsetStation_uid()
{
    m_Station_uidIsSet = false;
}

}
}
}
}


