/**
 * GSPNS / NSmart Public Transport API (Novi Sad)
 * Unofficial documentation of the reverse-engineered API behind the GSPNS (JGSP \"Novi Sad\") public transport network — the same API used by the **NSmart** mobile app (`buslogic.nsmartapp`).  The API is served by **BusLogic/NSmart** (`online.nsmart.rs`) and provides:  * the static transport network (cities → stations → line pairs), * real-time vehicle positions and arrival predictions per station, * electronic ticketing / wallet / card management endpoints (login, e-wallet, top-up…).  ## Reverse engineering provenance  * Endpoint paths, class names and the shared API key were recovered from the   NSmart 4.6 Android APK (see [FmasterofU/NSmart-RE](https://github.com/FmasterofU/NSmart-RE)). * Response schemas below were verified against the live API in September 2026. * The API key (`4670f468049bbee2260`) is compiled into the public APK as   `company_api_key` and is the same for every install — treat it as public knowledge.  ## Authentication  Every request must send the header:  ``` X-Api-Authentication: 4670f468049bbee2260 ```  All endpoints in this document include that header in their `security` requirements.  ## Notes & quirks (learned the hard way)  * The giant network payload (`networkextended.php`) is **not valid JSON when served   over a slow connection** — the server truncates / corrupts the stream mid-body   (raw control characters, null-byte runs, dropped chunks). The NSmart app   apparently tolerates this; re-request until you get a parseable body. * `networkextended.php` ignores semantically different `action` values   (`get_network`, `get_trips`, `get_schedule` return the same cities payload as   `get_cities_extended`). * `announcement.php` returns `[{\"success\":false,\"code\":3}]` for an unknown   `station_uid`. * `ibfm=TM00000` means \"all lines\"; pass a line code (e.g. `7A`) to filter. * Serbian text is `UTF-8`; strings may come back with JS-style unicode escapes. 
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.26.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "jgsp/model/ApiStatus.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

ApiStatus::ApiStatus()
{
    m_Success = false;
    m_SuccessIsSet = false;
    m_Msg = utility::conversions::to_string_t("");
    m_MsgIsSet = false;
    m_Code = 0;
    m_CodeIsSet = false;
}

ApiStatus::~ApiStatus()
{
}

void ApiStatus::validate()
{
    // TODO: implement validation
}

web::json::value ApiStatus::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_SuccessIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("success"))] = ModelBase::toJson(m_Success);
    }
    if(m_MsgIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("msg"))] = ModelBase::toJson(m_Msg);
    }
    if(m_CodeIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("code"))] = ModelBase::toJson(m_Code);
    }

    return val;
}

bool ApiStatus::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("success"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("success")));
        if(!fieldValue.is_null())
        {
            bool refVal_setSuccess;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSuccess);
            setSuccess(refVal_setSuccess);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("msg"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("msg")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setMsg;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMsg);
            setMsg(refVal_setMsg);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("code"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("code")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setCode;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCode);
            setCode(refVal_setCode);
            
        }
    }
    return ok;
}

void ApiStatus::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_SuccessIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("success")), m_Success));
    }
    if(m_MsgIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("msg")), m_Msg));
    }
    if(m_CodeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("code")), m_Code));
    }
}

bool ApiStatus::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("success"))))
    {
        bool refVal_setSuccess;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("success"))), refVal_setSuccess );
        setSuccess(refVal_setSuccess);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("msg"))))
    {
        utility::string_t refVal_setMsg;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("msg"))), refVal_setMsg );
        setMsg(refVal_setMsg);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("code"))))
    {
        int32_t refVal_setCode;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("code"))), refVal_setCode );
        setCode(refVal_setCode);
    }
    return ok;
}


bool ApiStatus::isSuccess() const
{
    return m_Success;
}

void ApiStatus::setSuccess(bool value)
{
    m_Success = value;
    m_SuccessIsSet = true;
}

bool ApiStatus::successIsSet() const
{
    return m_SuccessIsSet;
}

void ApiStatus::unsetSuccess()
{
    m_SuccessIsSet = false;
}
utility::string_t ApiStatus::getMsg() const
{
    return m_Msg;
}


void ApiStatus::setMsg(const utility::string_t& value)
{
    m_Msg = value;
    m_MsgIsSet = true;
}

bool ApiStatus::msgIsSet() const
{
    return m_MsgIsSet;
}

void ApiStatus::unsetMsg()
{
    m_MsgIsSet = false;
}
int32_t ApiStatus::getCode() const
{
    return m_Code;
}

void ApiStatus::setCode(int32_t value)
{
    m_Code = value;
    m_CodeIsSet = true;
}

bool ApiStatus::codeIsSet() const
{
    return m_CodeIsSet;
}

void ApiStatus::unsetCode()
{
    m_CodeIsSet = false;
}

}
}
}
}


