/**
 * GSPNS / NSmart Public Transport API (Novi Sad)
 * Unofficial documentation of the reverse-engineered API behind the GSPNS (JGSP \"Novi Sad\") public transport network — the same API used by the **NSmart** mobile app (`buslogic.nsmartapp`).  The API is served by **BusLogic/NSmart** (`online.nsmart.rs`) and provides:  * the static transport network (cities → stations → line pairs), * real-time vehicle positions and arrival predictions per station, * electronic ticketing / wallet / card management endpoints (login, e-wallet, top-up…).  ## Reverse engineering provenance  * Endpoint paths, class names and the shared API key were recovered from the   NSmart 4.6 Android APK (see [FmasterofU/NSmart-RE](https://github.com/FmasterofU/NSmart-RE)). * Response schemas below were verified against the live API in September 2026. * The API key (`4670f468049bbee2260`) is compiled into the public APK as   `company_api_key` and is the same for every install — treat it as public knowledge.  ## Authentication  Every request must send the header:  ``` X-Api-Authentication: 4670f468049bbee2260 ```  All endpoints in this document include that header in their `security` requirements.  ## Notes & quirks (learned the hard way)  * The giant network payload (`networkextended.php`) is **not valid JSON when served   over a slow connection** — the server truncates / corrupts the stream mid-body   (raw control characters, null-byte runs, dropped chunks). The NSmart app   apparently tolerates this; re-request until you get a parseable body. * `networkextended.php` ignores semantically different `action` values   (`get_network`, `get_trips`, `get_schedule` return the same cities payload as   `get_cities_extended`). * `announcement.php` returns `[{\"success\":false,\"code\":3}]` for an unknown   `station_uid`. * `ibfm=TM00000` means \"all lines\"; pass a line code (e.g. `7A`) to filter. * Serbian text is `UTF-8`; strings may come back with JS-style unicode escapes. 
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.26.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "jgsp/model/Coordinates.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

Coordinates::Coordinates()
{
    m_LatitudeIsSet = false;
    m_LongitudeIsSet = false;
}

Coordinates::~Coordinates()
{
}

void Coordinates::validate()
{
    // TODO: implement validation
}

web::json::value Coordinates::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_LatitudeIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("latitude"))] = ModelBase::toJson(m_Latitude);
    }
    if(m_LongitudeIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("longitude"))] = ModelBase::toJson(m_Longitude);
    }

    return val;
}

bool Coordinates::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("latitude"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("latitude")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Coordinates_latitude> refVal_setLatitude;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLatitude);
            setLatitude(refVal_setLatitude);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("longitude"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("longitude")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Coordinates_longitude> refVal_setLongitude;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLongitude);
            setLongitude(refVal_setLongitude);
            
        }
    }
    return ok;
}

void Coordinates::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_LatitudeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("latitude")), m_Latitude));
    }
    if(m_LongitudeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("longitude")), m_Longitude));
    }
}

bool Coordinates::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("latitude"))))
    {
        std::shared_ptr<Coordinates_latitude> refVal_setLatitude;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("latitude"))), refVal_setLatitude );
        setLatitude(refVal_setLatitude);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("longitude"))))
    {
        std::shared_ptr<Coordinates_longitude> refVal_setLongitude;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("longitude"))), refVal_setLongitude );
        setLongitude(refVal_setLongitude);
    }
    return ok;
}


std::shared_ptr<Coordinates_latitude> Coordinates::getLatitude() const
{
    return m_Latitude;
}


void Coordinates::setLatitude(const std::shared_ptr<Coordinates_latitude>& value)
{
    m_Latitude = value;
    m_LatitudeIsSet = true;
}

bool Coordinates::latitudeIsSet() const
{
    return m_LatitudeIsSet;
}

void Coordinates::unsetLatitude()
{
    m_LatitudeIsSet = false;
}
std::shared_ptr<Coordinates_longitude> Coordinates::getLongitude() const
{
    return m_Longitude;
}


void Coordinates::setLongitude(const std::shared_ptr<Coordinates_longitude>& value)
{
    m_Longitude = value;
    m_LongitudeIsSet = true;
}

bool Coordinates::longitudeIsSet() const
{
    return m_LongitudeIsSet;
}

void Coordinates::unsetLongitude()
{
    m_LongitudeIsSet = false;
}

}
}
}
}


