/**
 * GSPNS / NSmart Public Transport API (Novi Sad)
 * Unofficial documentation of the reverse-engineered API behind the GSPNS (JGSP \"Novi Sad\") public transport network — the same API used by the **NSmart** mobile app (`buslogic.nsmartapp`).  The API is served by **BusLogic/NSmart** (`online.nsmart.rs`) and provides:  * the static transport network (cities → stations → line pairs), * real-time vehicle positions and arrival predictions per station, * electronic ticketing / wallet / card management endpoints (login, e-wallet, top-up…).  ## Reverse engineering provenance  * Endpoint paths, class names and the shared API key were recovered from the   NSmart 4.6 Android APK (see [FmasterofU/NSmart-RE](https://github.com/FmasterofU/NSmart-RE)). * Response schemas below were verified against the live API in September 2026. * The API key (`4670f468049bbee2260`) is compiled into the public APK as   `company_api_key` and is the same for every install — treat it as public knowledge.  ## Authentication  Every request must send the header:  ``` X-Api-Authentication: 4670f468049bbee2260 ```  All endpoints in this document include that header in their `security` requirements.  ## Notes & quirks (learned the hard way)  * The giant network payload (`networkextended.php`) is **not valid JSON when served   over a slow connection** — the server truncates / corrupts the stream mid-body   (raw control characters, null-byte runs, dropped chunks). The NSmart app   apparently tolerates this; re-request until you get a parseable body. * `networkextended.php` ignores semantically different `action` values   (`get_network`, `get_trips`, `get_schedule` return the same cities payload as   `get_cities_extended`). * `announcement.php` returns `[{\"success\":false,\"code\":3}]` for an unknown   `station_uid`. * `ibfm=TM00000` means \"all lines\"; pass a line code (e.g. `7A`) to filter. * Serbian text is `UTF-8`; strings may come back with JS-style unicode escapes. 
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.26.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "jgsp/model/GetNetwork_200_response.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

GetNetwork_200_response::GetNetwork_200_response()
{
    m_CitiesIsSet = false;
}

GetNetwork_200_response::~GetNetwork_200_response()
{
}

void GetNetwork_200_response::validate()
{
    // TODO: implement validation
}

web::json::value GetNetwork_200_response::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_CitiesIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("cities"))] = ModelBase::toJson(m_Cities);
    }

    return val;
}

bool GetNetwork_200_response::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("cities"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("cities")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<City>> refVal_setCities;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCities);
            setCities(refVal_setCities);
            
        }
    }
    return ok;
}

void GetNetwork_200_response::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_CitiesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("cities")), m_Cities));
    }
}

bool GetNetwork_200_response::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("cities"))))
    {
        std::vector<std::shared_ptr<City>> refVal_setCities;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("cities"))), refVal_setCities );
        setCities(refVal_setCities);
    }
    return ok;
}


std::vector<std::shared_ptr<City>> GetNetwork_200_response::getCities() const
{
    return m_Cities;
}


void GetNetwork_200_response::setCities(const std::vector<std::shared_ptr<City>>& value)
{
    m_Cities = value;
    m_CitiesIsSet = true;
}

bool GetNetwork_200_response::citiesIsSet() const
{
    return m_CitiesIsSet;
}

void GetNetwork_200_response::unsetCities()
{
    m_CitiesIsSet = false;
}

}
}
}
}


