# coding: utf-8

"""
    GSPNS / NSmart Public Transport API (Novi Sad)

    Unofficial documentation of the reverse-engineered API behind the GSPNS (JGSP \"Novi Sad\") public transport network — the same API used by the **NSmart** mobile app (`buslogic.nsmartapp`).  The API is served by **BusLogic/NSmart** (`online.nsmart.rs`) and provides:  * the static transport network (cities → stations → line pairs), * real-time vehicle positions and arrival predictions per station, * electronic ticketing / wallet / card management endpoints (login, e-wallet, top-up…).  ## Reverse engineering provenance  * Endpoint paths, class names and the shared API key were recovered from the   NSmart 4.6 Android APK (see [FmasterofU/NSmart-RE](https://github.com/FmasterofU/NSmart-RE)). * Response schemas below were verified against the live API in September 2026. * The API key (`4670f468049bbee2260`) is compiled into the public APK as   `company_api_key` and is the same for every install — treat it as public knowledge.  ## Authentication  Every request must send the header:  ``` X-Api-Authentication: 4670f468049bbee2260 ```  All endpoints in this document include that header in their `security` requirements.  ## Notes & quirks (learned the hard way)  * The giant network payload (`networkextended.php`) is **not valid JSON when served   over a slow connection** — the server truncates / corrupts the stream mid-body   (raw control characters, null-byte runs, dropped chunks). The NSmart app   apparently tolerates this; re-request until you get a parseable body. * `networkextended.php` ignores semantically different `action` values   (`get_network`, `get_trips`, `get_schedule` return the same cities payload as   `get_cities_extended`). * `announcement.php` returns `[{\"success\":false,\"code\":3}]` for an unknown   `station_uid`. * `ibfm=TM00000` means \"all lines\"; pass a line code (e.g. `7A`) to filter. * Serbian text is `UTF-8`; strings may come back with JS-style unicode escapes. 

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jgsp_client.models.get_network_get200_response import GetNetworkGet200Response

class TestGetNetworkGet200Response(unittest.TestCase):
    """GetNetworkGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetNetworkGet200Response:
        """Test GetNetworkGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetNetworkGet200Response`
        """
        model = GetNetworkGet200Response()
        if include_optional:
            return GetNetworkGet200Response(
                cities = [
                    jgsp_client.models.city.City(
                        id = 72, 
                        name = 'Novi Sad', 
                        gbname = '', 
                        default_station = 7, 
                        coordinates = jgsp_client.models.coordinates.Coordinates(
                            latitude = 45.2671352, 
                            longitude = 19.8335496, ), 
                        country = jgsp_client.models.city_country.City_country(
                            name = 'Serbia', 
                            alpha2_code = 'RS', ), 
                        classes = '', 
                        stations = [6801,6548,6726,12883], 
                        pairs = [72,76,1473,72], 
                        slugs = 'novisad', 
                        has_train_station = False, )
                    ]
            )
        else:
            return GetNetworkGet200Response(
        )
        """

    def testGetNetworkGet200Response(self):
        """Test GetNetworkGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
