/* tslint:disable */
/* eslint-disable */
/**
 * GSPNS / NSmart Public Transport API (Novi Sad)
 * Unofficial documentation of the reverse-engineered API behind the GSPNS (JGSP \"Novi Sad\") public transport network — the same API used by the **NSmart** mobile app (`buslogic.nsmartapp`).  The API is served by **BusLogic/NSmart** (`online.nsmart.rs`) and provides:  * the static transport network (cities → stations → line pairs), * real-time vehicle positions and arrival predictions per station, * electronic ticketing / wallet / card management endpoints (login, e-wallet, top-up…).  ## Reverse engineering provenance  * Endpoint paths, class names and the shared API key were recovered from the   NSmart 4.6 Android APK (see [FmasterofU/NSmart-RE](https://github.com/FmasterofU/NSmart-RE)). * Response schemas below were verified against the live API in September 2026. * The API key (`4670f468049bbee2260`) is compiled into the public APK as   `company_api_key` and is the same for every install — treat it as public knowledge.  ## Authentication  Every request must send the header:  ``` X-Api-Authentication: 4670f468049bbee2260 ```  All endpoints in this document include that header in their `security` requirements.  ## Notes & quirks (learned the hard way)  * The giant network payload (`networkextended.php`) is **not valid JSON when served   over a slow connection** — the server truncates / corrupts the stream mid-body   (raw control characters, null-byte runs, dropped chunks). The NSmart app   apparently tolerates this; re-request until you get a parseable body. * `networkextended.php` ignores semantically different `action` values   (`get_network`, `get_trips`, `get_schedule` return the same cities payload as   `get_cities_extended`). * `announcement.php` returns `[{\"success\":false,\"code\":3}]` for an unknown   `station_uid`. * `ibfm=TM00000` means \"all lines\"; pass a line code (e.g. `7A`) to filter. * Serbian text is `UTF-8`; strings may come back with JS-style unicode escapes. 
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CityCountry } from './CityCountry';
import {
    CityCountryFromJSON,
    CityCountryFromJSONTyped,
    CityCountryToJSON,
    CityCountryToJSONTyped,
} from './CityCountry';
import type { Coordinates } from './Coordinates';
import {
    CoordinatesFromJSON,
    CoordinatesFromJSONTyped,
    CoordinatesToJSON,
    CoordinatesToJSONTyped,
} from './Coordinates';

/**
 * A city (municipality) in the GSPNS network.
 * @export
 * @interface City
 */
export interface City {
    /**
     * City ID. Novi Sad = 72.
     */
    id: number;
    /**
     * City name (UTF-8, may contain escaped characters).
     */
    name: string;
    /**
     * Google Business / geocoding name override (often empty).
     */
    gbname?: string;
    /**
     * Default (central) station ID for the city. Novi Sad = 7.
     */
    defaultStation: number;
    /**
     * 
     */
    coordinates: Coordinates;
    /**
     * 
     */
    country: CityCountry;
    /**
     * Pipe/format string of fare classes (usually empty in the raw payload).
     */
    classes?: string;
    /**
     * All station IDs belonging to the city.
     */
    stations: Array<number>;
    /**
     * Line-pair IDs per station (used for route reconstruction).
     */
    pairs: Array<number>;
    /**
     * URL/geo slug of the city.
     */
    slugs: string;
    /**
     * Whether the city has a railway station.
     */
    hasTrainStation: boolean;
}

/**
 * Check if a given object implements the City interface.
 */
export function instanceOfCity(value: object): value is City {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if ((!('defaultStation' in (value as Record<string, any>)) && !('default_station' in (value as Record<string, any>))) || ((value as Record<string, any>)['defaultStation'] === undefined && (value as Record<string, any>)['default_station'] === undefined)) return false;
    if (!('coordinates' in value) || value['coordinates'] === undefined) return false;
    if (!('country' in value) || value['country'] === undefined) return false;
    if (!('stations' in value) || value['stations'] === undefined) return false;
    if (!('pairs' in value) || value['pairs'] === undefined) return false;
    if (!('slugs' in value) || value['slugs'] === undefined) return false;
    if ((!('hasTrainStation' in (value as Record<string, any>)) && !('has_train_station' in (value as Record<string, any>))) || ((value as Record<string, any>)['hasTrainStation'] === undefined && (value as Record<string, any>)['has_train_station'] === undefined)) return false;
    return true;
}

export function CityFromJSON(json: any): City {
    return CityFromJSONTyped(json, false);
}

export function CityFromJSONTyped(json: any, ignoreDiscriminator: boolean): City {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'gbname': json['gbname'] == null ? undefined : json['gbname'],
        'defaultStation': json['default_station'],
        'coordinates': CoordinatesFromJSON(json['coordinates']),
        'country': CityCountryFromJSON(json['country']),
        'classes': json['classes'] == null ? undefined : json['classes'],
        'stations': json['stations'],
        'pairs': json['pairs'],
        'slugs': json['slugs'],
        'hasTrainStation': json['has_train_station'],
    };
}

export function CityToJSON(json: any): City {
    return CityToJSONTyped(json, false);
}

export function CityToJSONTyped(value?: City | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'gbname': value['gbname'],
        'default_station': value['defaultStation'],
        'coordinates': CoordinatesToJSON(value['coordinates']),
        'country': CityCountryToJSON(value['country']),
        'classes': value['classes'],
        'stations': value['stations'],
        'pairs': value['pairs'],
        'slugs': value['slugs'],
        'has_train_station': value['hasTrainStation'],
    };
}

