/* tslint:disable */
/* eslint-disable */
/**
 * GSPNS / NSmart Public Transport API (Novi Sad)
 * Unofficial documentation of the reverse-engineered API behind the GSPNS (JGSP \"Novi Sad\") public transport network — the same API used by the **NSmart** mobile app (`buslogic.nsmartapp`).  The API is served by **BusLogic/NSmart** (`online.nsmart.rs`) and provides:  * the static transport network (cities → stations → line pairs), * real-time vehicle positions and arrival predictions per station, * electronic ticketing / wallet / card management endpoints (login, e-wallet, top-up…).  ## Reverse engineering provenance  * Endpoint paths, class names and the shared API key were recovered from the   NSmart 4.6 Android APK (see [FmasterofU/NSmart-RE](https://github.com/FmasterofU/NSmart-RE)). * Response schemas below were verified against the live API in September 2026. * The API key (`4670f468049bbee2260`) is compiled into the public APK as   `company_api_key` and is the same for every install — treat it as public knowledge.  ## Authentication  Every request must send the header:  ``` X-Api-Authentication: 4670f468049bbee2260 ```  All endpoints in this document include that header in their `security` requirements.  ## Notes & quirks (learned the hard way)  * The giant network payload (`networkextended.php`) is **not valid JSON when served   over a slow connection** — the server truncates / corrupts the stream mid-body   (raw control characters, null-byte runs, dropped chunks). The NSmart app   apparently tolerates this; re-request until you get a parseable body. * `networkextended.php` ignores semantically different `action` values   (`get_network`, `get_trips`, `get_schedule` return the same cities payload as   `get_cities_extended`). * `announcement.php` returns `[{\"success\":false,\"code\":3}]` for an unknown   `station_uid`. * `ibfm=TM00000` means \"all lines\"; pass a line code (e.g. `7A`) to filter. * Serbian text is `UTF-8`; strings may come back with JS-style unicode escapes. 
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CoordinatesLongitude } from './CoordinatesLongitude';
import {
    CoordinatesLongitudeFromJSON,
    CoordinatesLongitudeFromJSONTyped,
    CoordinatesLongitudeToJSON,
    CoordinatesLongitudeToJSONTyped,
} from './CoordinatesLongitude';
import type { CoordinatesLatitude } from './CoordinatesLatitude';
import {
    CoordinatesLatitudeFromJSON,
    CoordinatesLatitudeFromJSONTyped,
    CoordinatesLatitudeToJSON,
    CoordinatesLatitudeToJSONTyped,
} from './CoordinatesLatitude';

/**
 * Geographic coordinates. Values are numbers (cities) or strings (stations).
 * @export
 * @interface Coordinates
 */
export interface Coordinates {
    /**
     * 
     */
    latitude?: CoordinatesLatitude;
    /**
     * 
     */
    longitude?: CoordinatesLongitude;
}

/**
 * Check if a given object implements the Coordinates interface.
 */
export function instanceOfCoordinates(value: object): value is Coordinates {
    return true;
}

export function CoordinatesFromJSON(json: any): Coordinates {
    return CoordinatesFromJSONTyped(json, false);
}

export function CoordinatesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Coordinates {
    if (json == null) {
        return json;
    }
    return {
        
        'latitude': json['latitude'] == null ? undefined : CoordinatesLatitudeFromJSON(json['latitude']),
        'longitude': json['longitude'] == null ? undefined : CoordinatesLongitudeFromJSON(json['longitude']),
    };
}

export function CoordinatesToJSON(json: any): Coordinates {
    return CoordinatesToJSONTyped(json, false);
}

export function CoordinatesToJSONTyped(value?: Coordinates | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'latitude': CoordinatesLatitudeToJSON(value['latitude']),
        'longitude': CoordinatesLongitudeToJSON(value['longitude']),
    };
}

