/* tslint:disable */
/* eslint-disable */
/**
 * GSPNS / NSmart Public Transport API (Novi Sad)
 * Unofficial documentation of the reverse-engineered API behind the GSPNS (JGSP \"Novi Sad\") public transport network — the same API used by the **NSmart** mobile app (`buslogic.nsmartapp`).  The API is served by **BusLogic/NSmart** (`online.nsmart.rs`) and provides:  * the static transport network (cities → stations → line pairs), * real-time vehicle positions and arrival predictions per station, * electronic ticketing / wallet / card management endpoints (login, e-wallet, top-up…).  ## Reverse engineering provenance  * Endpoint paths, class names and the shared API key were recovered from the   NSmart 4.6 Android APK (see [FmasterofU/NSmart-RE](https://github.com/FmasterofU/NSmart-RE)). * Response schemas below were verified against the live API in September 2026. * The API key (`4670f468049bbee2260`) is compiled into the public APK as   `company_api_key` and is the same for every install — treat it as public knowledge.  ## Authentication  Every request must send the header:  ``` X-Api-Authentication: 4670f468049bbee2260 ```  All endpoints in this document include that header in their `security` requirements.  ## Notes & quirks (learned the hard way)  * The giant network payload (`networkextended.php`) is **not valid JSON when served   over a slow connection** — the server truncates / corrupts the stream mid-body   (raw control characters, null-byte runs, dropped chunks). The NSmart app   apparently tolerates this; re-request until you get a parseable body. * `networkextended.php` ignores semantically different `action` values   (`get_network`, `get_trips`, `get_schedule` return the same cities payload as   `get_cities_extended`). * `announcement.php` returns `[{\"success\":false,\"code\":3}]` for an unknown   `station_uid`. * `ibfm=TM00000` means \"all lines\"; pass a line code (e.g. `7A`) to filter. * Serbian text is `UTF-8`; strings may come back with JS-style unicode escapes. 
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { City } from './City';
import {
    CityFromJSON,
    CityFromJSONTyped,
    CityToJSON,
    CityToJSONTyped,
} from './City';

/**
 * 
 * @export
 * @interface GetNetworkGet200Response
 */
export interface GetNetworkGet200Response {
    /**
     * 
     */
    cities?: Array<City>;
}

/**
 * Check if a given object implements the GetNetworkGet200Response interface.
 */
export function instanceOfGetNetworkGet200Response(value: object): value is GetNetworkGet200Response {
    return true;
}

export function GetNetworkGet200ResponseFromJSON(json: any): GetNetworkGet200Response {
    return GetNetworkGet200ResponseFromJSONTyped(json, false);
}

export function GetNetworkGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetNetworkGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'cities': json['cities'] == null ? undefined : ((json['cities'] as Array<any>).map(CityFromJSON)),
    };
}

export function GetNetworkGet200ResponseToJSON(json: any): GetNetworkGet200Response {
    return GetNetworkGet200ResponseToJSONTyped(json, false);
}

export function GetNetworkGet200ResponseToJSONTyped(value?: GetNetworkGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cities': value['cities'] == null ? undefined : ((value['cities'] as Array<any>).map(CityToJSON)),
    };
}

