/**
 * GSPNS / NSmart Public Transport API (Novi Sad)
 * Unofficial documentation of the reverse-engineered API behind the GSPNS (JGSP \"Novi Sad\") public transport network — the same API used by the **NSmart** mobile app (`buslogic.nsmartapp`).  The API is served by **BusLogic/NSmart** (`online.nsmart.rs`) and provides:  * the static transport network (cities → stations → line pairs), * real-time vehicle positions and arrival predictions per station, * electronic ticketing / wallet / card management endpoints (login, e-wallet, top-up…).  ## Reverse engineering provenance  * Endpoint paths, class names and the shared API key were recovered from the   NSmart 4.6 Android APK (see [FmasterofU/NSmart-RE](https://github.com/FmasterofU/NSmart-RE)). * Response schemas below were verified against the live API in September 2026. * The API key (`4670f468049bbee2260`) is compiled into the public APK as   `company_api_key` and is the same for every install — treat it as public knowledge.  ## Authentication  Every request must send the header:  ``` X-Api-Authentication: 4670f468049bbee2260 ```  All endpoints in this document include that header in their `security` requirements.  ## Notes & quirks (learned the hard way)  * The giant network payload (`networkextended.php`) is **not valid JSON when served   over a slow connection** — the server truncates / corrupts the stream mid-body   (raw control characters, null-byte runs, dropped chunks). The NSmart app   apparently tolerates this; re-request until you get a parseable body. * `networkextended.php` ignores semantically different `action` values   (`get_network`, `get_trips`, `get_schedule` return the same cities payload as   `get_cities_extended`). * `announcement.php` returns `[{\"success\":false,\"code\":3}]` for an unknown   `station_uid`. * `ibfm=TM00000` means \"all lines\"; pass a line code (e.g. `7A`) to filter. * Serbian text is `UTF-8`; strings may come back with JS-style unicode escapes. 
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.26.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * PaymentsApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_PaymentsApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_PaymentsApi_H_



#include "jgsp/ApiClient.h"
#include "jgsp/ModelBase.h"
#include "jgsp/Object.h"
#include <cpprest/details/basic_types.h>
#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  PaymentsApi 
{
public:

    explicit PaymentsApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~PaymentsApi();

    /// <summary>
    /// AllSecure payment operations
    /// </summary>
    /// <remarks>
    /// Payment gateway (AllSecure / Credorax) integration used for card payments, tokenization and validation. Class names in the APK: &#x60;AllSecureValidationApi&#x60;, &#x60;AllSecureFinalizeApi&#x60;, &#x60;AllSecureCheckStatusApi&#x60;. 
    /// </remarks>
    /// <param name="action">e.g. validate, finalize, check_status</param>
    pplx::task<std::shared_ptr<Object>> allsecurePayment(
        utility::string_t action
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_PaymentsApi_H_ */

