/**
 * GSPNS / NSmart Public Transport API (Novi Sad)
 * Unofficial documentation of the reverse-engineered API behind the GSPNS (JGSP \"Novi Sad\") public transport network — the same API used by the **NSmart** mobile app (`buslogic.nsmartapp`).  The API is served by **BusLogic/NSmart** (`online.nsmart.rs`) and provides:  * the static transport network (cities → stations → line pairs), * real-time vehicle positions and arrival predictions per station, * electronic ticketing / wallet / card management endpoints (login, e-wallet, top-up…).  ## Reverse engineering provenance  * Endpoint paths, class names and the shared API key were recovered from the   NSmart 4.6 Android APK (see [FmasterofU/NSmart-RE](https://github.com/FmasterofU/NSmart-RE)). * Response schemas below were verified against the live API in September 2026. * The API key (`4670f468049bbee2260`) is compiled into the public APK as   `company_api_key` and is the same for every install — treat it as public knowledge.  ## Authentication  Every request must send the header:  ``` X-Api-Authentication: 4670f468049bbee2260 ```  All endpoints in this document include that header in their `security` requirements.  ## Notes & quirks (learned the hard way)  * The giant network payload (`networkextended.php`) is **not valid JSON when served   over a slow connection** — the server truncates / corrupts the stream mid-body   (raw control characters, null-byte runs, dropped chunks). The NSmart app   apparently tolerates this; re-request until you get a parseable body. * `networkextended.php` ignores semantically different `action` values   (`get_network`, `get_trips`, `get_schedule` return the same cities payload as   `get_cities_extended`). * `announcement.php` returns `[{\"success\":false,\"code\":3}]` for an unknown   `station_uid`. * `ibfm=TM00000` means \"all lines\"; pass a line code (e.g. `7A`) to filter. * Serbian text is `UTF-8`; strings may come back with JS-style unicode escapes. 
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.26.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * RealtimeApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_RealtimeApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_RealtimeApi_H_



#include "jgsp/ApiClient.h"

#include "jgsp/model/Announcement.h"
#include <vector>
#include <cpprest/details/basic_types.h>
#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  RealtimeApi 
{
public:

    explicit RealtimeApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~RealtimeApi();

    /// <summary>
    /// Get live arrivals &amp; vehicle positions for a station
    /// </summary>
    /// <remarks>
    /// Returns real-time departure/arrival predictions for every upcoming vehicle at the given station. Each entry describes one approaching vehicle: seconds left until it reaches the station, its current GPS position, how many stations away it is, the garage (vehicle) number, and the full station sequence of its line.  Use &#x60;ibfm&#x3D;TM00000&#x60; for all lines, or a specific line code (e.g. &#x60;7A&#x60;) to filter. 
    /// </remarks>
    /// <param name="ibfm">Line filter. &#x60;TM00000&#x60; &#x3D; all lines; otherwise a line code such as &#x60;7A&#x60; or &#x60;8&#x60;.</param>
    /// <param name="stationUid">Station ID (see network endpoint for the full station list). E.g. 6532 &#x3D; \&quot;Narodnog fronta-Šekspirova\&quot;.</param>
    pplx::task<std::vector<std::shared_ptr<Announcement>>> getStationAnnouncements(
        utility::string_t ibfm,
        int32_t stationUid
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_RealtimeApi_H_ */

