/*
GSPNS / NSmart Public Transport API (Novi Sad)

Unofficial documentation of the reverse-engineered API behind the GSPNS (JGSP \"Novi Sad\") public transport network — the same API used by the **NSmart** mobile app (`buslogic.nsmartapp`).  The API is served by **BusLogic/NSmart** (`online.nsmart.rs`) and provides:  * the static transport network (cities → stations → line pairs), * real-time vehicle positions and arrival predictions per station, * electronic ticketing / wallet / card management endpoints (login, e-wallet, top-up…).  ## Reverse engineering provenance  * Endpoint paths, class names and the shared API key were recovered from the   NSmart 4.6 Android APK (see [FmasterofU/NSmart-RE](https://github.com/FmasterofU/NSmart-RE)). * Response schemas below were verified against the live API in September 2026. * The API key (`4670f468049bbee2260`) is compiled into the public APK as   `company_api_key` and is the same for every install — treat it as public knowledge.  ## Authentication  Every request must send the header:  ``` X-Api-Authentication: 4670f468049bbee2260 ```  All endpoints in this document include that header in their `security` requirements.  ## Notes & quirks (learned the hard way)  * The giant network payload (`networkextended.php`) is **not valid JSON when served   over a slow connection** — the server truncates / corrupts the stream mid-body   (raw control characters, null-byte runs, dropped chunks). The NSmart app   apparently tolerates this; re-request until you get a parseable body. * `networkextended.php` ignores semantically different `action` values   (`get_network`, `get_trips`, `get_schedule` return the same cities payload as   `get_cities_extended`). * `announcement.php` returns `[{\"success\":false,\"code\":3}]` for an unknown   `station_uid`. * `ibfm=TM00000` means \"all lines\"; pass a line code (e.g. `7A`) to filter. * Serbian text is `UTF-8`; strings may come back with JS-style unicode escapes. 

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package jgsp

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetNetworkRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetNetworkRequest{}

// GetNetworkRequest struct for GetNetworkRequest
type GetNetworkRequest struct {
	// Action verb. Observed values all return the same network payload.
	Action string `json:"action"`
}

type _GetNetworkRequest GetNetworkRequest

// NewGetNetworkRequest instantiates a new GetNetworkRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetNetworkRequest(action string) *GetNetworkRequest {
	this := GetNetworkRequest{}
	this.Action = action
	return &this
}

// NewGetNetworkRequestWithDefaults instantiates a new GetNetworkRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetNetworkRequestWithDefaults() *GetNetworkRequest {
	this := GetNetworkRequest{}
	var action string = "get_cities_extended"
	this.Action = action
	return &this
}

// GetAction returns the Action field value
func (o *GetNetworkRequest) GetAction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *GetNetworkRequest) GetActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *GetNetworkRequest) SetAction(v string) {
	o.Action = v
}

func (o GetNetworkRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetNetworkRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["action"] = o.Action
	return toSerialize, nil
}

func (o *GetNetworkRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"action",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetNetworkRequest := _GetNetworkRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetNetworkRequest)

	if err != nil {
		return err
	}

	*o = GetNetworkRequest(varGetNetworkRequest)

	return err
}

type NullableGetNetworkRequest struct {
	value *GetNetworkRequest
	isSet bool
}

func (v NullableGetNetworkRequest) Get() *GetNetworkRequest {
	return v.value
}

func (v *NullableGetNetworkRequest) Set(val *GetNetworkRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGetNetworkRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGetNetworkRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetNetworkRequest(val *GetNetworkRequest) *NullableGetNetworkRequest {
	return &NullableGetNetworkRequest{value: val, isSet: true}
}

func (v NullableGetNetworkRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetNetworkRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


