/*
GSPNS / NSmart Public Transport API (Novi Sad)

Unofficial documentation of the reverse-engineered API behind the GSPNS (JGSP \"Novi Sad\") public transport network — the same API used by the **NSmart** mobile app (`buslogic.nsmartapp`).  The API is served by **BusLogic/NSmart** (`online.nsmart.rs`) and provides:  * the static transport network (cities → stations → line pairs), * real-time vehicle positions and arrival predictions per station, * electronic ticketing / wallet / card management endpoints (login, e-wallet, top-up…).  ## Reverse engineering provenance  * Endpoint paths, class names and the shared API key were recovered from the   NSmart 4.6 Android APK (see [FmasterofU/NSmart-RE](https://github.com/FmasterofU/NSmart-RE)). * Response schemas below were verified against the live API in September 2026. * The API key (`4670f468049bbee2260`) is compiled into the public APK as   `company_api_key` and is the same for every install — treat it as public knowledge.  ## Authentication  Every request must send the header:  ``` X-Api-Authentication: 4670f468049bbee2260 ```  All endpoints in this document include that header in their `security` requirements.  ## Notes & quirks (learned the hard way)  * The giant network payload (`networkextended.php`) is **not valid JSON when served   over a slow connection** — the server truncates / corrupts the stream mid-body   (raw control characters, null-byte runs, dropped chunks). The NSmart app   apparently tolerates this; re-request until you get a parseable body. * `networkextended.php` ignores semantically different `action` values   (`get_network`, `get_trips`, `get_schedule` return the same cities payload as   `get_cities_extended`). * `announcement.php` returns `[{\"success\":false,\"code\":3}]` for an unknown   `station_uid`. * `ibfm=TM00000` means \"all lines\"; pass a line code (e.g. `7A`) to filter. * Serbian text is `UTF-8`; strings may come back with JS-style unicode escapes. 

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package jgsp

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VehiclePosition type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VehiclePosition{}

// VehiclePosition Live GPS position of a vehicle.
type VehiclePosition struct {
	// Vehicle/garage number.
	GarageNo string `json:"garageNo"`
	// Latitude as string.
	Lat string `json:"lat"`
	// Longitude as string.
	Lng string `json:"lng"`
}

type _VehiclePosition VehiclePosition

// NewVehiclePosition instantiates a new VehiclePosition object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVehiclePosition(garageNo string, lat string, lng string) *VehiclePosition {
	this := VehiclePosition{}
	this.GarageNo = garageNo
	this.Lat = lat
	this.Lng = lng
	return &this
}

// NewVehiclePositionWithDefaults instantiates a new VehiclePosition object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVehiclePositionWithDefaults() *VehiclePosition {
	this := VehiclePosition{}
	return &this
}

// GetGarageNo returns the GarageNo field value
func (o *VehiclePosition) GetGarageNo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GarageNo
}

// GetGarageNoOk returns a tuple with the GarageNo field value
// and a boolean to check if the value has been set.
func (o *VehiclePosition) GetGarageNoOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GarageNo, true
}

// SetGarageNo sets field value
func (o *VehiclePosition) SetGarageNo(v string) {
	o.GarageNo = v
}

// GetLat returns the Lat field value
func (o *VehiclePosition) GetLat() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Lat
}

// GetLatOk returns a tuple with the Lat field value
// and a boolean to check if the value has been set.
func (o *VehiclePosition) GetLatOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Lat, true
}

// SetLat sets field value
func (o *VehiclePosition) SetLat(v string) {
	o.Lat = v
}

// GetLng returns the Lng field value
func (o *VehiclePosition) GetLng() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Lng
}

// GetLngOk returns a tuple with the Lng field value
// and a boolean to check if the value has been set.
func (o *VehiclePosition) GetLngOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Lng, true
}

// SetLng sets field value
func (o *VehiclePosition) SetLng(v string) {
	o.Lng = v
}

func (o VehiclePosition) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VehiclePosition) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["garageNo"] = o.GarageNo
	toSerialize["lat"] = o.Lat
	toSerialize["lng"] = o.Lng
	return toSerialize, nil
}

func (o *VehiclePosition) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"garageNo",
		"lat",
		"lng",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVehiclePosition := _VehiclePosition{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVehiclePosition)

	if err != nil {
		return err
	}

	*o = VehiclePosition(varVehiclePosition)

	return err
}

type NullableVehiclePosition struct {
	value *VehiclePosition
	isSet bool
}

func (v NullableVehiclePosition) Get() *VehiclePosition {
	return v.value
}

func (v *NullableVehiclePosition) Set(val *VehiclePosition) {
	v.value = val
	v.isSet = true
}

func (v NullableVehiclePosition) IsSet() bool {
	return v.isSet
}

func (v *NullableVehiclePosition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVehiclePosition(val *VehiclePosition) *NullableVehiclePosition {
	return &NullableVehiclePosition{value: val, isSet: true}
}

func (v NullableVehiclePosition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVehiclePosition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


