/*
GSPNS / NSmart Public Transport API (Novi Sad)

Unofficial documentation of the reverse-engineered API behind the GSPNS (JGSP \"Novi Sad\") public transport network — the same API used by the **NSmart** mobile app (`buslogic.nsmartapp`).  The API is served by **BusLogic/NSmart** (`online.nsmart.rs`) and provides:  * the static transport network (cities → stations → line pairs), * real-time vehicle positions and arrival predictions per station, * electronic ticketing / wallet / card management endpoints (login, e-wallet, top-up…).  ## Reverse engineering provenance  * Endpoint paths, class names and the shared API key were recovered from the   NSmart 4.6 Android APK (see [FmasterofU/NSmart-RE](https://github.com/FmasterofU/NSmart-RE)). * Response schemas below were verified against the live API in September 2026. * The API key (`4670f468049bbee2260`) is compiled into the public APK as   `company_api_key` and is the same for every install — treat it as public knowledge.  ## Authentication  Every request must send the header:  ``` X-Api-Authentication: 4670f468049bbee2260 ```  All endpoints in this document include that header in their `security` requirements.  ## Notes & quirks (learned the hard way)  * The giant network payload (`networkextended.php`) is **not valid JSON when served   over a slow connection** — the server truncates / corrupts the stream mid-body   (raw control characters, null-byte runs, dropped chunks). The NSmart app   apparently tolerates this; re-request until you get a parseable body. * `networkextended.php` ignores semantically different `action` values   (`get_network`, `get_trips`, `get_schedule` return the same cities payload as   `get_cities_extended`). * `announcement.php` returns `[{\"success\":false,\"code\":3}]` for an unknown   `station_uid`. * `ibfm=TM00000` means \"all lines\"; pass a line code (e.g. `7A`) to filter. * Serbian text is `UTF-8`; strings may come back with JS-style unicode escapes. 

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package jgsp

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetNetwork200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetNetwork200Response{}

// GetNetwork200Response struct for GetNetwork200Response
type GetNetwork200Response struct {
	// All cities in the network
	Cities []City `json:"cities"`
}

type _GetNetwork200Response GetNetwork200Response

// NewGetNetwork200Response instantiates a new GetNetwork200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetNetwork200Response(cities []City) *GetNetwork200Response {
	this := GetNetwork200Response{}
	this.Cities = cities
	return &this
}

// NewGetNetwork200ResponseWithDefaults instantiates a new GetNetwork200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetNetwork200ResponseWithDefaults() *GetNetwork200Response {
	this := GetNetwork200Response{}
	return &this
}

// GetCities returns the Cities field value
func (o *GetNetwork200Response) GetCities() []City {
	if o == nil {
		var ret []City
		return ret
	}

	return o.Cities
}

// GetCitiesOk returns a tuple with the Cities field value
// and a boolean to check if the value has been set.
func (o *GetNetwork200Response) GetCitiesOk() ([]City, bool) {
	if o == nil {
		return nil, false
	}
	return o.Cities, true
}

// SetCities sets field value
func (o *GetNetwork200Response) SetCities(v []City) {
	o.Cities = v
}

func (o GetNetwork200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetNetwork200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cities"] = o.Cities
	return toSerialize, nil
}

func (o *GetNetwork200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"cities",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetNetwork200Response := _GetNetwork200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetNetwork200Response)

	if err != nil {
		return err
	}

	*o = GetNetwork200Response(varGetNetwork200Response)

	return err
}

type NullableGetNetwork200Response struct {
	value *GetNetwork200Response
	isSet bool
}

func (v NullableGetNetwork200Response) Get() *GetNetwork200Response {
	return v.value
}

func (v *NullableGetNetwork200Response) Set(val *GetNetwork200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetNetwork200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetNetwork200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetNetwork200Response(val *GetNetwork200Response) *NullableGetNetwork200Response {
	return &NullableGetNetwork200Response{value: val, isSet: true}
}

func (v NullableGetNetwork200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetNetwork200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


