# coding: utf-8

# flake8: noqa

"""
    GSPNS / NSmart Public Transport API (Novi Sad)

    Unofficial documentation of the reverse-engineered API behind the GSPNS (JGSP \"Novi Sad\") public transport network — the same API used by the **NSmart** mobile app (`buslogic.nsmartapp`).  The API is served by **BusLogic/NSmart** (`online.nsmart.rs`) and provides:  * the static transport network (cities → stations → line pairs), * real-time vehicle positions and arrival predictions per station, * electronic ticketing / wallet / card management endpoints (login, e-wallet, top-up…).  ## Reverse engineering provenance  * Endpoint paths, class names and the shared API key were recovered from the   NSmart 4.6 Android APK (see [FmasterofU/NSmart-RE](https://github.com/FmasterofU/NSmart-RE)). * Response schemas below were verified against the live API in September 2026. * The API key (`4670f468049bbee2260`) is compiled into the public APK as   `company_api_key` and is the same for every install — treat it as public knowledge.  ## Authentication  Every request must send the header:  ``` X-Api-Authentication: 4670f468049bbee2260 ```  All endpoints in this document include that header in their `security` requirements.  ## Notes & quirks (learned the hard way)  * The giant network payload (`networkextended.php`) is **not valid JSON when served   over a slow connection** — the server truncates / corrupts the stream mid-body   (raw control characters, null-byte runs, dropped chunks). The NSmart app   apparently tolerates this; re-request until you get a parseable body. * `networkextended.php` ignores semantically different `action` values   (`get_network`, `get_trips`, `get_schedule` return the same cities payload as   `get_cities_extended`). * `announcement.php` returns `[{\"success\":false,\"code\":3}]` for an unknown   `station_uid`. * `ibfm=TM00000` means \"all lines\"; pass a line code (e.g. `7A`) to filter. * Serbian text is `UTF-8`; strings may come back with JS-style unicode escapes. 

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "AccountApi",
    "MiscApi",
    "NetworkApi",
    "PaymentsApi",
    "RealtimeApi",
    "WalletCardsApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AccountAction200Response",
    "Announcement",
    "AnnouncementAllStationsInner",
    "ApiStatus",
    "City",
    "CityCountry",
    "Coordinates",
    "CoordinatesLatitude",
    "CoordinatesLongitude",
    "GetNetwork200Response",
    "GetNetworkGet200Response",
    "GetNetworkRequest",
    "VehiclePosition",
]

# import apis into sdk package
from jgsp_client.api.account_api import AccountApi as AccountApi
from jgsp_client.api.misc_api import MiscApi as MiscApi
from jgsp_client.api.network_api import NetworkApi as NetworkApi
from jgsp_client.api.payments_api import PaymentsApi as PaymentsApi
from jgsp_client.api.realtime_api import RealtimeApi as RealtimeApi
from jgsp_client.api.wallet_cards_api import WalletCardsApi as WalletCardsApi

# import ApiClient
from jgsp_client.api_response import ApiResponse as ApiResponse
from jgsp_client.api_client import ApiClient as ApiClient
from jgsp_client.configuration import Configuration as Configuration
from jgsp_client.exceptions import OpenApiException as OpenApiException
from jgsp_client.exceptions import ApiTypeError as ApiTypeError
from jgsp_client.exceptions import ApiValueError as ApiValueError
from jgsp_client.exceptions import ApiKeyError as ApiKeyError
from jgsp_client.exceptions import ApiAttributeError as ApiAttributeError
from jgsp_client.exceptions import ApiException as ApiException

# import models into sdk package
from jgsp_client.models.account_action200_response import AccountAction200Response as AccountAction200Response
from jgsp_client.models.announcement import Announcement as Announcement
from jgsp_client.models.announcement_all_stations_inner import AnnouncementAllStationsInner as AnnouncementAllStationsInner
from jgsp_client.models.api_status import ApiStatus as ApiStatus
from jgsp_client.models.city import City as City
from jgsp_client.models.city_country import CityCountry as CityCountry
from jgsp_client.models.coordinates import Coordinates as Coordinates
from jgsp_client.models.coordinates_latitude import CoordinatesLatitude as CoordinatesLatitude
from jgsp_client.models.coordinates_longitude import CoordinatesLongitude as CoordinatesLongitude
from jgsp_client.models.get_network200_response import GetNetwork200Response as GetNetwork200Response
from jgsp_client.models.get_network_get200_response import GetNetworkGet200Response as GetNetworkGet200Response
from jgsp_client.models.get_network_request import GetNetworkRequest as GetNetworkRequest
from jgsp_client.models.vehicle_position import VehiclePosition as VehiclePosition

